### ISSUE TITLE
How to hide 'ALL' and 'NONE' buttons if not required?

### ISSUE THREAD

**Issue by AbGrS** [czeckd/angular-dual-listbox#36]
I mean I can do through CSS but are there any params which i can disable or something to hide these buttons

**Comment by czeckd** [comment]
There's no parameter to diable/hide the buttons. Either hide through CSS or extend the component and omit including the buttons in the html template.

**Comment by jaschulz** [comment]
Hi, @czeckd. I know this is an old issue, but i was wondering if you could give me some guidance to hide the buttons through CSS.  This is what I've tried, without success.
My css:
button.btn-block {
    display: none !important;
}

I did this, trying to overwrite the following, hence the '!important':

button.btn-block {
    display: block;
    width: 100%;
    margin-bottom: 8px;
}

Am I missing something?

**Comment by czeckd** [comment]
In your app's base styles:
```css
div.dual-list div.listbox button[name=addBtn],
div.dual-list div.listbox button[name=removeBtn],
div.dual-list div.listbox div.button-bar {
  display: none;
}
```
